<a href="https://colab.research.google.com/github/stefanoridolfi/Coding_ML/blob/master/vettori_prodotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tmp = output_errors * output_vector_network * (1.0 - output_vector_network)  = [[-0.12240776  0.12259739]] output_errors= [[-0.48963132  0.49038987]] output_vector_network= [[0.49963132 0.49961013]] 1.0 - output_vector_network= [[0.50036868 0.50038987]] FFFF

In [31]:
import numpy as np
a= [[1, 2], [3, 4]]
b= [[2, 2], [1, 1]]
m32=[(1, 2), (1, 3),(3,4)]
v21=(1,2)
v21=np.array(v21).T
m32=np.array(m32)
m32v21=m32.dot(v21)
print("vettore 2 x 1\n",v21.shape, v21)
print("matrice 3 x 2, dimensioni ",m32.shape,"\n", m32)
print("matrice 2 x 3, dimensioni ",m32.T.shape,"\n", m32.T)

print("vettore 3 x 1\n",m32v21)

a=np.array(a,ndmin=2)
b=np.array(b,ndmin=2)
adotb=np.dot(a,b)
print("a=",a)
print("b=",b)
print("a_dot_b=",adotb)
avettb=a*b
print("prodotto vettoriale",avettb)

vettore 2 x 1
 (2,) [1 2]
matrice 3 x 2, dimensioni  (3, 2) 
 [[1 2]
 [1 3]
 [3 4]]
matrice 2 x 3, dimensioni  (2, 3) 
 [[1 1 3]
 [2 3 4]]
vettore 3 x 1
 [ 5  7 11]
a= [[1 2]
 [3 4]]
b= [[2 2]
 [1 1]]
a_dot_b= [[ 4  4]
 [10 10]]
prodotto vettoriale [[2 4]
 [3 4]]
